# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(QtWidgets.QMainWindow):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(291, 209)
        self.label = QtWidgets.QLabel(Window)
        self.label.setGeometry(QtCore.QRect(110, 10, 71, 31))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Window)
        self.label_5.setGeometry(QtCore.QRect(40, 130, 180, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Window)
        self.pushButton.setGeometry(QtCore.QRect(190, 170, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Window)
        self.widget.setGeometry(QtCore.QRect(40, 50, 206, 50))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "about"))
        self.label.setText(_translate("Window", "http cat"))
        self.label_5.setText(_translate("Window", "make&open source  by cacaview and GNUv3"))
        self.pushButton.setText(_translate("Window", "关闭"))
        self.label_2.setText(_translate("Window", "httpcat 版本1.2"))
        self.label_3.setText(_translate("Window", "httpcat是一个能快速从httpcat和"))
        self.label_4.setText(_translate("Window", "httpdog处获得图片的软件。"))
