# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\set.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_set(QtWidgets.QMainWindow):
    def setupUi(self, set):
        set.setObjectName("set")
        set.resize(400, 300)
        self.label = QtWidgets.QLabel(set)
        self.label.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(set)
        self.comboBox.setGeometry(QtCore.QRect(70, 40, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(set)
        self.pushButton.setGeometry(QtCore.QRect(300, 250, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.comboBox.addItems(["http cat", "http dog"])

        self.retranslateUi(set)
        QtCore.QMetaObject.connectSlotsByName(set)

    def retranslateUi(self, set):
        _translate = QtCore.QCoreApplication.translate
        set.setWindowTitle(_translate("set", "Form"))
        self.label.setText(_translate("set", "请求源："))
        self.pushButton.setText(_translate("set", "确认"))
